test
SergeyAlexandrowich/portfolio pull request #1
Opened 2023-07-19 00:14 UTC by SergeyAlexandrowich

2023-07-19 00:23 UTC, naumch1k requested changes

2023-07-19 00:23 UTC, naumch1k commented on index.html
> +            <h2 id="recent-works">Works</h2>
Dct [thyz - `gthtltksdfq`

`<h1>...</h1>`

2023-07-19 00:23 UTC, naumch1k commented on index.html
>      <main class="main">
gfggfgfg

2023-07-19 00:27 UTC, SergeyAlexandrowich commented on index.html
> +            <h2 id="recent-works">Works</h2>
Ира, я не понимаю
Давай на украинском

2023-07-19 00:43 UTC, SergeyAlexandrowich commented on index.html
> +            <h2 id="recent-works">Works</h2>
Іра, все виправив
Перевір, як зможеш

2023-07-19 00:49 UTC, naumch1k requested changes

2023-07-19 00:49 UTC, naumch1k commented on index.html
> +                    <img class="main__works-photo rotation" src="images/accomodation.png"></a>
  аяаяаяаяй! Что это за микс? А где Стили? А почему CCS нет?

2023-07-26 01:24 UTC, naumch1k commented on css/styles.css
> +
Сережа, а че тут так много пробелов?))

2023-08-29 04:51 UTC, merged